### ISSUE TITLE
Migrate Firefox for iOS to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#102]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next l10n deadline: August 11

## Shipping locales

- [x] af
- [x] ar
- [x] br
- [x] ca
- [x] cy
- [x] dsb
- [x] eu
- [x] fa
- [x] ga-IE
- [x] gd
- [x] hi
- [x] hsb
- [x] is
- [x] kk
- [x] lt
- [x] ne
- [x] pt-PT
- [x] son
- [x] ta
- [x] uz

## Locales-in-progress

- [x] bs
- [x] kn
- [ ] tn

**Comment by Delphine** [comment]
We're likely getting a string export for the end of next week, Friday August 11th. Given the l10n mobile schedule, and comparing it with our Pontoon deadline, this needs to move before August 11th.
Since we're all traveling for a big chunk of next week, I'm thinking I should do this sooner than later. I'll do this next Tues, August 8th (same day as the Focus Android migration)

**Comment by Delphine** [comment]
Sent initial email to all managers of locales listed here.
Posted entire mobile schedule on dev.l10n: https://groups.google.com/forum/#!topic/mozilla.dev.l10n/906xzujhdsk

(also unchecking now all the little boxes because I was too zealous and thus misinterpreted what they were for ;) )

**Comment by Delphine** [comment]
Done! Note that "tn" locale has probably been added here by mistake because they don't have activity. So we didn't migrate/enable it in Pontoon
