### ISSUE TITLE
Jakarta Rocket Sprint Planning (quick overview)

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/pm-projects#131]
- [x] Agenda for Aug 11-12 
- [x] Create wiki 
- [x] Set up locales in Pontoon
- [x] Define invitation criteria and identify the invitees
- [x] Create and send registration form for dietary need and t-shirt size
- [X] Budget for meals: 2xbreakfast, 2xlunch, 3xdinner and snacks/tea
- [X] Things to bring to event from MV office: Android phones, t-shirts, lanyards&badges, and stickers
- [x] Telegram Channel

**Comment by Delphine** [comment]
Thanks for filing this!
Took the liberty of un-checking some items since they aren't done yet.

I'd say yes, we need a wiki since we usually use that as the single source of truth during the event. We'll also need a Telegram channel for the event (will add that to the list). I'll also add a cultural outing, if possible.

I'll add everything here because I'm not sure if you wanted to create just one issue for this event.

**Comment by Delphine** [comment]
Seems like @gueroJeff wants to order updated gear for this year: see #137
If it's ready for Paris, it'll be ready for this event as well.
The list of tasks here is thus getting longer, and I'm inclined to suggest we should have a project for this - and maybe divide up the issues?

**Comment by gueroJeff** [comment]
Yes, we should track this as its own event project.

**Comment by peiying2** [comment]
https://github.com/mozilla-l10n/pm-projects/projects/17

**Comment by Delphine** [comment]
Thanks Peiying. 
I was wondering if there was a reason the project was made using Notes instead of issues (like in https://github.com/mozilla-l10n/pm-projects/projects/16#card-10796730 + all other event projects)?
The thing is, I wanted to add comments but I don't think I can since they are under the Notes format. It seems that it limits our current use of the project? Also, there's no way to know who added what if you just edit, I believe. This probably needs to be converted into issues, and get corresponding labels? (unless I'm missing something behind the current rational :) ).

**Comment by peiying2** [comment]
Let's convert it. Operator errors, :). I am not using the feature correctly. Let me clean it up.
