### ISSUE TITLE
Validate results of LexiQA analysis on Italian

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#181]
We need to validate the results of the LexiQA analysis on Italian.

**Comment by flodolo** [comment]
This depends on a new analysis: https://github.com/mozilla-l10n/pm-projects/issues/184

For reference, the first analysis with Pontoon's TMX resulted in 

```
General statistics
16,965 potential errors found in 65,076 words
Error ratio: 0.261
------------------------------------------------------------
43% of these potential errors relate to spelling (7,388)
35% relate to punctuation (5,942)
6% are untranslated segments (1,098)
13% are inconsistencies (204 in source, 133 in target)
The rest (3%) relate to URLs (7), numerals (88), symbols (122) and glossaries (21)
```

**Comment by flodolo** [comment]
Results for cleaned up TMX

```
General statistics
5,737 potential errors found in 16,965 words
Error ratio: 0.089
------------------------------------------------------------
spelling (1,355)
punctuation (706)
untranslated segments (983)
inconsistencies (379 in source, 203 in target)
URLs (7), numerals (77), symbols (128) and glossaries (30)
```

**Comment by flodolo** [comment]
## Punctuation

In Italian we don't use as many exclamation points as English; we either remove them, or replace them with a period. In other cases, it's marketing (CTA) content changed into a question.

There are still a lot of false positives:
- Remaining Fluent code, like `PLATFORM` triggers errors like `segment starting with a space`.
- Things like `about:addons` or `net.nz`.
- [Plural forms](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Use_proper_plural_forms) in .properties, where `;` is used as separator for plural forms.
- Strings ending with brand entities in DTDs (`&brandShortName`).
- Capitalization required after a period, when it's an abbreviation (`Scad. mese`).

I wasn't able to identify any actual issue in this group.

## Numerals

Lot of false positives related to Unicode endpoints converted to UTF-8 characters, print placeables like `%0.S`.

Other errors reported are unclear:
-`Rallentata (0.5×)` says `Number not found in source`, when the source is `Slow (0.5×)`.
-`index not found in source`, when both contain `C++`.

Not sure if it expects the number to be formatted (1,3 vs 1.3).

Only one actual error found (`Japanese (ISO-2022-JP)`).

## Links

All errors reported are actual issues in the source, where `en-US` should be left out from links to MDN. They're simply too old to fix.

`name@example.com` is correct, since we localize the first part of the address.

## Symbols

Lot of false positive:
- Fluent terms.
- Fluent syntax (asterisk for default variant).
- Ordered vs unordered printf placeables (`%S %S` and `%1$S %2$S` are equivalent).
- Checks get really confused around `<` and `>`. For example, the entire content between them is considered as a tag in `Saw “<” when expecting an attribute name. Probable cause: Missing “>” immediately before.`.

Unclear errors:
- `Placeholder missing from target`, but source is `{ $frames -> [one] { $type } Image (animated, { $frames } frame) *[other] { $type } Image (animated, { $frames } frames) }` and target is `{ $type } Immagine (animata, { $frames } frame)`.
– `Faroe Islands` translated as `Isole Fær Øer` is reported as an error.

One actual error found.

## Empty

DTDs require concatenating to inject HTML (start + link + end), which means strings can be empty, in either source and target, but not necessarily both at the same time. The other is an unused file that should have been filtered out of the TMX.

## Glossaries

The system can't distinguish "Sync" as a feature name, from "Sync" as a verb when it's at the beginning of a sentence. All other cases have "Firefox" removed as a subject, since we try to not personalize the software where possible.

## Spelling

A few classes of false positives:
- The spellchecker doesn't recognize the typographical apostrophe as a separator, and consider things like `dell’utente finale` as a single misspelled word.
- A lot of terms need to remain untranslated. Some of this could be mitigated by having a larger glossary, but for some contexts (devtools) that would bring more risk than help (missing actual misspelled words).
- Abbreviations.
- CSS rules.
- Capitalization differences (why are these reported as spelling issues?).

There are some words spelled correctly but reported.

## Inconsistent

Two main issues:
- Tool can't account for adjectives being declined according to number and gender (active -> attivo, attiva, attivi).
- Tool can't account for context. A string that can be fully displayed on desktop ("Aggiungi componente aggiuntivo") needs to be shortened on mobile ("Agg. comp. aggiuntivo"), or a different dialog, while English can keep using the same text. Same is valid for capitalization, or role in a dialog (title vs button label).
- There are still some single letter strings left (acccesskeys, commandkeys).

**Comment by flodolo** [comment]
I assume this can be considered completed.

**Comment by gueroJeff** [comment]
Yes, we're continuing this with mobile products instead, so we can close this and I'll open a new one for that.
