### ISSUE TITLE
Create Smartling template for app store content

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#246]
Create a standard template for translating app store content through Smartling. Template must be a .csv file with the appropriate Smartling directives. Template must be discoverable to marketing teams.

The following specifications must be met for an app store content template:

**Comment by peiying2** [comment]
Templates and examples for [Mobile in-prod description](https://drive.google.com/drive/folders/1WlHpe3ZWvBDPP4ihBf9IkN6lTN9Z5U46) request:
- [x] Instruction and process for requester and copy preparer.
- [x] Mobile in-prod description copy template with directives in spreadsheet
- [x] Export of the template in .csv
- [x] Example of localized file downloaded from Smartling
- [x] Example of localized file delivered to customer. 

@gueroJeff ready for review. The template is a large because the actual request is usually this big. The formula would allow calculation of the entire block of text which consists of multiple strings.

**Comment by gueroJeff** [comment]
lgtm
