### ISSUE TITLE
Create script to reformat Smartlink markdown output

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/pm-projects#273]
This conversion script is needed for the style guide (and will be leveraged for Legal docs).
- [Source file](https://github.com/mozilla-l10n/styleguides/blob/master/docs/guidelines/firefox_marketing.md)
- [Issues encountered](https://github.com/mozilla-l10n/styleguides/pull/169)
- [All the style guides](https://drive.google.com/drive/folders/1To8MKiSXh5FHAAlSvNsR9V1fjYNEUD-K) exported from Smartling (except for German and French)

Known issue: A space is added between a stylized word and a punctuation. If there is no immediate fix from the vendor side, it will require a manual fix.

**Comment by flodolo** [comment]
> and will be leveraged for Legal docs

I don't think that will be possible, because I don't know the style used by that repository (and I doubt they enforce one?). I'd say we should limit the scope to style guides, and then who manages technically the legal docs can make a decision, and eventually use the script as a base.

**Comment by peiying2** [comment]
> > and will be leveraged for Legal docs
> 
> I don't think that will be possible, because I don't know the style used by that repository (and I doubt they enforce one?). I'd say we should limit the scope to style guides, and then who manages technically the legal docs can make a decision, and eventually use the script as a base.

pmac will help with the legal doc linter, but most likely, he will leverage your work.

**Comment by flodolo** [comment]
I think I tried all possible combinations, but I can't seem to be able to run the script in automation (it will fail if the branch comes from a fork and not the main repository).

At this point, the only solution left is to run the script locally:
1. You create your pull requests with your files, as you'd normally do.
2. You run the following script from the root of the repository `bash .github/scripts/reformat_files_pr.sh mozilla-l10n/styleguides 173`. The only thing that changes is the last number, which is the pull request number created in the first step.
3. You check the changes and commit them.

The changes should be relatively safe, but things might break differently with a new set of files.

Can you try creating a new pull request with some file, run the script and see if it works for you? Make sure to update your master branch before trying, otherwise you won't have the script.

**Comment by flodolo** [comment]
Alternatively, I could change the script so that it reformats all the files with pending changes. But I think creating the PR and commit changes separately helps catching errors.

**Comment by flodolo** [comment]
You can see the changes here
https://github.com/flodolo/styleguides/pull/4/commits/d8a4759462b26441e88fc6085e809512119dab2d

**Comment by flodolo** [comment]
> I think I tried all possible combinations, but I can't seem to be able to run the script in automation (it will fail if the branch comes from a fork and not the main repository).

I decided to give it another ago, let's see if I can figure out something next week, or if that's a limitation in the GitHub action I'm using and it's impossible to work around it.

**Comment by flodolo** [comment]
There is now some sort of automation, although it's far from ideal:
1. It only runs if you open a pull request from a branch in the same repository, not from a fork
2. You need to add the *smartling* tag when you open the pull request (before creating it), otherwise automation won't trigger
3. It commits the changes to the same branch, so you need to pull before making further changes locally (e.g. the Indonesian test still had errors, since the file wasn't referenced in SUMMARY.md)
4. The check shows up in the original commit, not in the additional one ([see PR](https://github.com/mozilla-l10n/styleguides/pull/174)).

I have an open issue to try to solve the fork issue (1), but I doubt there's a solution (it's a permissions problem). 

I don't want to run the script on all PRs, which causes (2).

**Comment by peiying2** [comment]
The script worked!! I have uploaded all the files to the repo and merged them. In the process I found a few mistakes I would like to try fixing:
- SUMMARY.md hi should be hi-IN/firefox_marketing.md
- Punctuation and spacing: this still is the case with zh-CN and zh-TW. (ko has not issue, ja avoids the format in heading).
- Curly quotes (it, pt-BR) in both single and double. 

Initial try was without the Smartling label (I thought the files were converted, so no need to use the label). It didn't work. I tried again with the label added, and the PR still failed. I tried to fix the hi locale change only,  it still doesn't work. Check out this  [PR188](https://github.com/mozilla-l10n/styleguides/pull/188) and the closed PRs before this.

**Comment by flodolo** [comment]
I forgot to account for a clean PR (with no errors), it should be fixed now.

https://github.com/mozilla-l10n/styleguides/pull/188 is still failing because of another error (zh-CN missing). Note that I had to rebase and force push, so you need `git pull;git reset --hard origin/FormatCleanup` if you want to make further changes locally.

> Punctuation and spacing: this still is the case with zh-CN and zh-TW. (ko has not issue, ja avoids the format in heading).

Can you clarify this?

> Curly quotes (it, pt-BR) in both single and double.

To be clear, that's a Smartling problem (translators), not the Linter's job. Are we on the same page?

**Comment by flodolo** [comment]
I actually went ahead, fixed and merged that PR, since it was just a misspelled locale code.

Still unclear of what the problem was with zh-CN and zh-TW, I didn't spot any when I test with those files.

**Comment by peiying2** [comment]
> I forgot to account for a clean PR (with no errors), it should be fixed now.
> 
> [mozilla-l10n/styleguides#188](https://github.com/mozilla-l10n/styleguides/pull/188) is still failing because of another error (zh-CN missing from SUMMARY).
> 
> ```
> There are markdown files not referenced in SUMMARY.md
>   - zh-CN/firefox_marketing.md
> ```
I missed it. Thanks for the fix.

> Note that I had to rebase and force push, so you need `git pull;git reset --hard origin/FormatCleanup` if you want to make further changes locally.

I will make sure to rebase before making more edits.
> 
> > Punctuation and spacing: this still is the case with zh-CN and zh-TW. (ko has not issue, ja avoids the format in heading).
> 
> Can you clarify this?

Check both locales in lines 13, 21, 25, 29, 52
> 
> > Curly quotes (it, pt-BR) in both single and double.
> 
> To be clear, that's a Smartling problem (translators), not the Linter's job. Are we on the same page?

Correct, I didn't expect the Linter to catch this. It was an afterthought to check. This is a translator issue.

**Comment by peiying2** [comment]
> I actually went ahead, fixed and merged that PR, since it was just a misspelled locale code.
> 
> Still unclear of what the problem was with zh-CN and zh-TW, I didn't spot any when I test with those files.

Check both locales in lines 13, 21, 25, 29, 52

**Comment by flodolo** [comment]
> Check both locales in lines 13, 21, 25, 29, 52

Ah, that's because they use a different character instead of a normal colon (the script tries to limit the places were space is removed). That's probably fixable.

**Comment by flodolo** [comment]
See https://github.com/mozilla-l10n/styleguides/pull/189

**Comment by peiying2** [comment]
I think we can close this issue now. It is done!

**Comment by flodolo** [comment]
There might be need to tweak the script if more strange characters come up, but that's relatively easy to do.
