### ISSUE TITLE
Taipei Goals & Agenda

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#34]
# Core focus:
- Rebuilding communities
- Evangelizing localized products
- Quality
- Training on tooling changes

# Outcomes:
- Localizers can recruit and train new localizers.
- Each community's language resources (style guides, term lists) are created & up-to-date.
- Marked improvement in localization quality for l10n projects.
- Localizers trained in translation process best practices.

# Format:
## Day 1:
**Morning**
- Spectograms
- Org updates

**Afternoon**
- Common goals breakouts
- Free time (goals work, 1:1 time with l10n-drivers, community visits with l10n-drivers)
## Day 2:
- Common goals breakouts
- Free time (goals work, 1:1 time with l10n-drivers, community visits with l10n-drivers)

# Planning:
The l10n-drivers will coordinate among l10n communities to identify common goals and split up time into breakout sessions. Otherwise, we will only need a few hours in the first morning to accomplish our own goals (give Mozilla org updates, roadmap updates, l10n program updates, etc.). 

The content and goals for the afternoons and the second morning are entirely open for the communities to fill with what they feel is most worthy of their time. Here are some questions that can help guide defining what this time could be filled with:
- What does the l10n community hope to accomplish during the hackathon?
- Are open, group discussions more valuable or are breakouts more valuable?
- Would there be value in holding an open public time during the hackathon?
- What does the l10n community hope to bring back to their larger community?

**Comment by peiying2** [comment]
@petercpg, we can start planning.

**Comment by petercpg** [comment]
roger that. let me form up a preliminary with other community people first and comment back soon :)

**Comment by petercpg** [comment]
I’m not so sure about each team’s situation so here are some discussions I had with Lora:
Participants are going to do some planning works, especially for items above in Core Focus. For smaller teams, hackathon can be used to finish some small but critical l10n works, but I think it’s too expensive to do the generic l10n stuffs. We can also provide helps on l10n tool transition to Pontoon (are we going to do this?)

I would also like to give some thought for some questions above:

- Are open, group discussions more valuable or are breakouts more valuable?
  They are both valuable IMO, but depending on what goals each locale team have. 
  - If we want to do more tasks like finish l10n progress, or making up style guides, breakouts would be preferred.
  - If we want to do more plannings or discussion, like recruitment strategy or annual goals, group discussions will be preferred.
- Would there be value in holding an open public time during the hackathon?
  Yes, open time will be valuable, but it need a kickstart for people to speak to exchange, instead of talking to their own team fellows. I see it a great chance for locale teams to exchange ideas with other teams, especially in this face-to-face event.
  This time I would like to add a time for each team go to center, and give a small talk about:
  - Brief introduction
  - What project(s) are your team working on, and your progress,
  - Team, and maybe personal goal & objectives
  - What difficulties do you have,
  - Any question wanted to ask advice from other teams,
  - Anything wanted to share with other teams
  - (feel free to add something)

  It can be like a 5-min show-and-tell for each team, when everyone know little about you, the discuss can start further in public time. What do you think, @peiying2 ?

**Comment by peiying2** [comment]
@petercpg & @shadowcrow, thanks for putting this together!

Agreed!  We can solicit goals through email communications, like we did last time. Although people tend to copy others when they don't have specific goals in mind yet.  There is nothing wrong about it, but this makes many teams wait and see until much later in the planning to come up with something.  

I like the idea of giving each  team a chance to speak in front of others. This could be challenging for some teams/people.  We can make it mandate that they have to prepare something or it is totally voluntary.  

For group discussion, once we see a common theme (or themes) that surface from the team planning phase, we select one topic or two per afternoon session and address that. It is less about the drivers have all the solutions or answers, but we all of us will come together think of the topics and brainstorm how we can do better, improve.

**Comment by petercpg** [comment]
Exactly, actually speaking in front of others is a challenge for me too :~ 
What task(s) do you think we should begin with? I guess invitation, or budgets?

**Comment by gueroJeff** [comment]
Event wiki page created: https://wiki.mozilla.org/L10n:Meetings/2017_Taipei_Workshop

Please begin planning goals & agenda.
