### ISSUE TITLE
Taipei Logistics

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#44]
- [x] Identify & book venue location
- [x] Identify & book hotel for localizers
- [x] Book travel for localizers
- [x] Find & book restaurants or catering for 2 lunches & 3 dinners.
- [x] Identify visa needs.
- [x] Identify transportation needs and make necessary arrangements.
- [ ] Get name tags and gear for localizers.
- [x] Identify possible cultural activities.
- [x] Create Telegram group.

**Comment by peiying2** [comment]
Filed a service request per WPR's guidance for use of TPE office spaceWPR0051994

**Comment by nth10sd** [comment]
Some tips:

* The Mozilla Taiwan office is in the Xinyi (信義) district, and hotels around them can be pricey. Some Mozilla folks (and me) have greater value in staying in comfortable hotels slightly further (a few subway stops away) for about half price, in the Dongmen (東門) district. It should be just as safe.
  * Examples: [Rido Hotel](https://goo.gl/maps/taN62SxK1CP2) near Da'an Park (大安森林公園), and [Royal Biz](https://goo.gl/maps/u6xQfsqEAWD2)
  * Airbnb is less recommended because Mandarin is largely spoken among locals, not all will be fluent in English. Some addresses (when translated to English) can be hard to locate in-person.
* Transport
  * The Taoyuan Metro is scheduled to be open in March 2017, but has been delayed multiple times in the past few years.
  * In case it gets delayed, it is suggested to have someone to meet community members on arrival.
  * It is possible to take public buses (客運) to the city but it is more difficult for a non-Mandarin speaker to do so.
  * Taxis are also an option (and are somewhat affordable, TWD1300 to the city, or US$30-40) but while the dispatchers do understand English, not all taxi drivers do.
    * When departing, folks should take taxis to the airport
  * Local transport card (悠遊卡)
    * This card pays for convenient subway and bus rides. We should have a set budget for folks to get around the city
* Catering has historically been done by the Taipei office folks. We should contact them.
  * Everyone there has catered lunches except Fridays
  * Catered lunches usually have vegetarian options available (again, double-check)
  * We have to look out separately for Halal food, perhaps have a separate liaison take Muslim folks out for meals. Locals should be consulted.
* Food suggestions:
  * For soup dumplings, one of the most famous is Ding Tai Fung (鼎泰豐) in A4 near the office takes reservations, the 101 branch does not, and the original branch at Dongmen does not take credit card payment.
  * Addiction Aquatic Development (上引水產) is a seafood place near Xing Tian Gong (行天宮). Takes reservations, but cash-only.
  * Hot-pot (spicy or otherwise), e.g. Taihodien (太和殿) or 這一鍋
  * Local restaurants (e.g. 熱炒) 
* Cultural activities (all optional)
  * In previous work weeks, folks have been brought to local temples (e.g. Xing Tian Gong 行天宮) to experience local religious worship practices. Attendance is optional.
  * Night markets. Raohe (饒河) and Shida (師大) night markets are popular spots.
* Nature activities:
  * Hiking up Elephant Hill (象山), located fairly close to the office
  * The Maokong Gondola (貓空纜車) is located at the outskirts of Taipei and features outstanding views of the city.

**Comment by petercpg** [comment]
I have merged these suggestions to the doc. Thanks @nth10sd and feel free to add more idea.

**Comment by peiying2** [comment]
We have completed all but two items listed above:
- gear, name tag - this is WIP
- Telegram group - this will be created two weeks prior to the event.
